# the osft config will override default ppo_trainer.yaml

hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

trainer:
  enable_train_temperature: false # make tau_t=tau_s or not, default is set them different and tau_t=1

actor_rollout_ref:
  actor:
    optim:
      lr_warmup_steps: 10
    entropy_coeff: 0
  rollout:
    tensor_model_parallel_size: 1

algorithm:
  adv_estimator: null

ray_init:
  num_cpus: 64